mysite/mysite/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('polls.urls', namespace='polls1')),
    # url(r'', include('polls2.urls', namespace='polls2')),
]

mysite/polls/urls.py
from django.conf.urls import include, url, patterns
from polls import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
]

mysite/polls/models.py
from django.db import models

# Create your models here.

mysite/polls2/models.py
from django.db import models

# Create your models here.

mysite/polls3/models.py
from django.db import models

# Create your models here.

mysite/polls/views.py
from django.shortcuts import render

# Create your views here.


# def home(request):
#     """
#     Evaluation of tweets
#     :param request:
#     :return:
#     """
    #config_train, train = home.models.Configuration.objects.get_or_create(name=common.TRAIN_CONFIG_NAME)
    #if request.method == 'POST':
    #    evaluation_form = EvaluationForm(request.POST)
    #    if evaluation_form.is_valid():
    #        evaluation_form.save()
    #        min_next_eval_tweet_id = get_next_tweet_to_evaluate()
    #        evaluation_form = EvaluationForm(initial={'tweet': min_next_eval_tweet_id})
    #    else:
    #        pass
    #else:
    #    evaluation_form = None
    #    if not config_train.enable:
    #        min_next_eval_tweet_id = get_next_tweet_to_evaluate()
    #        evaluation_form = EvaluationForm(initial={'tweet': min_next_eval_tweet_id})

    #data_dictionary = {
    #    "config_train_enable" : config_train.enable,
    #    'evaluation_form': evaluation_form
    #}

    # return render(request, 'polls/home.html', data_dictionary)

def home(request):
    data_dictionary = {
        'data' : None,
    }
    return render(request, 'polls/twitter_home.html', data_dictionary)

def about(request):
    return render(request, 'polls/twitter_about.html', {})

mysite/polls2/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls3/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/templates/polls/about_section.html
   <!-- ******ABOUT****** -->
    <section id="about" class="about section">
        <div class="container">
            <h2 class="title text-center">What is devAid?</h2>
            <p class="intro text-center">Explain your project in detail. Ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
            <div class="row">
                <div class="item col-md-4 col-sm-6 col-xs-12">
                    <div class="icon-holder">
                        <i class="fa fa-heart"></i>
                    </div>
                    <div class="content">
                        <h3 class="sub-title">Designed for developers</h3>
                        <p>Outline a benefit here. Tell users what your plugin/software can do for them. You can change the icon above to any of the 400+ <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">FontAwesome</a> icons available.</p>
                    </div><!--//content-->
                </div><!--//item-->
                <div class="item col-md-4 col-sm-6 col-xs-12">
                    <div class="icon-holder">
                        <i class="fa fa-clock-o"></i>
                    </div>
                    <div class="content">
                        <h3 class="sub-title">Time saver</h3>
                        <p>Outline a benefit here. Tell users what your plugin/software can do for them. You can change the icon above to any of the 400+ <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">FontAwesome</a> icons available.</p>
                    </div><!--//content-->
                </div><!--//item-->
                <div class="item col-md-4 col-sm-6 col-xs-12">
                    <div class="icon-holder">
                        <i class="fa fa-crosshairs"></i>
                    </div>
                    <div class="content">
                        <h3 class="sub-title">UX-centred</h3>
                        <p>Outline a benefit here. Tell users what your plugin/software can do for them. You can change the icon above to any of the 400+ <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">FontAwesome</a> icons available.</p>
                    </div><!--//content-->
                </div><!--//item-->
                <div class="clearfix visible-md"></div>
                <div class="item col-md-4 col-sm-6 col-xs-12">
                    <div class="icon-holder">
                        <i class="fa fa-tablet"></i>
                    </div>
                    <div class="content">
                        <h3 class="sub-title">Mobile-friendly</h3>
                        <p>Outline a benefit here. Tell users what your plugin/software can do for them. You can change the icon above to any of the 400+ <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">FontAwesome</a> icons available.</p>
                    </div><!--//content-->
                </div><!--//item-->
                <div class="item col-md-4 col-sm-6 col-xs-12">
                    <div class="icon-holder">
                        <i class="fa fa-code"></i>
                    </div>
                    <div class="content">
                        <h3 class="sub-title">Easy to customise</h3>
                        <p>Outline a benefit here. Tell users what your plugin/software can do for them. You can change the icon above to any of the 400+ <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">FontAwesome</a> icons available.</p>
                    </div><!--//content-->
                </div><!--//item-->
                <div class="item col-md-4 col-sm-6 col-xs-12">
                    <div class="icon-holder">
                        <i class="fa fa-coffee"></i>
                    </div>
                    <div class="content">
                        <h3 class="sub-title">LESS files included</h3>
                        <p>Outline a benefit here. Tell users what your plugin/software can do for them. You can change the icon above to any of the 400+ <a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">FontAwesome</a> icons available.</p>
                    </div><!--//content-->
                </div><!--//item-->
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//about-->

mysite/polls/templates/polls/features_section.html
    <!-- ******FEATURES****** -->
    <section id="features" class="features section">
        <div class="container text-center">
            <h2 class="title">Features</h2>
            <ul class="feature-list list-unstyled">
                <li><i class="fa fa-check"></i> Fully responsive</li>
                <li><i class="fa fa-check"></i> HTML5 + CSS3</li>
                <li><i class="fa fa-check"></i> Built on <a href="http://getbootstrap.com/" target="_blank">Bootstrap 3.3</a></li>
                <li><i class="fa fa-check"></i> 400+ FontAwesome icons</li>
                <li><i class="fa fa-check"></i> 4 colour schemes</li>
                <li><i class="fa fa-check"></i> LESS files included</li>
                <li><i class="fa fa-check"></i> Compatible with all modern browsers</li>
            </ul>
        </div><!--//container-->
    </section><!--//features-->

mysite/polls/templates/polls/header.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}


    <title>Free Bootstrap Theme for Developers</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- Global CSS -->

    <link rel="stylesheet" href="{% static "plugins/bootstrap/css/bootstrap.min.css" %}">
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="{% static "plugins/font-awesome/css/font-awesome.css" %}">
    <link rel="stylesheet" href="{% static "plugins/prism/prism.css" %}">
    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static "css/styles.css" %}">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

mysite/polls/templates/polls/license_section.html
    <!-- ******LICENSE****** -->
    <section id="license" class="license section">
        <div class="container">
            <div class="license-inner">
            <h2 class="title text-center">License</h2>
                <div class="info">
                    <p>This Bootstrap theme is made by UX designer <a href="https://www.linkedin.com/in/xiaoying" target="_blank">Xiaoying Riley</a> at 3rd Wave Media for developers and is <strong>100% FREE</strong> under the <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons Attribution 3.0 License (CC BY 3.0)</a></p>
                    <p><strong>[Tip for developers]:</strong> If your project is open source, you might want to put a <a href="https://www.paypal.com/us/cgi-bin/?cmd=_donate-intro-outside" target="_blank">PayPal "Donate" button</a> below so your users can express their gratitude. If your project is commercial, you can put a <a href="https://www.paypal.com/us/cgi-bin/webscr?cmd=_singleitem-intro-outside" target="_blank">PayPal "Buy Now" button</a> instead.</p>
                </div><!--//info-->
                <div class="cta-container">
                    <div class="speech-bubble">
                        <p class="intro">If you are feeling generous and want to show your support to Xiaoying, you can buy her a beer or coffee via the PayPal donate button below. :)</p>
                        <div class="icon-holder  text-center"><i class="fa fa-smile-o"></i></div>
                    </div><!--//speech-bubble-->
                    <div class="btn-container  text-center">
                        <!--//You need to generate your own PayPal button - https://www.paypal.com/us/cgi-bin/?cmd=_donate-intro-outside -->
                        <!--PayPal generated code starts-->
                        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                        <input type="hidden" name="cmd" value="_s-xclick">
                        <input type="hidden" name="hosted_button_id" value="Y46LJNXGAVVWW">
                        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                        <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                        </form>
                        <!--//PayPal generated code ends-->

                    </div><!--//btn-container-->
                </div><!--//cta-container-->
            </div><!--//license-inner-->
        </div><!--//container-->
    </section><!--//how-->

mysite/polls/templates/polls/pay.html
{% load nvd3_tags %}
<head>
    <!--- include char jssc -->
    {% include_chart_jscss %}
    {% load_chart charttype chartdata chartcontainer extra %}
    <!--- load -->
{#    {% load_chart charttype chartdata "linechart_container" extra %}#}
    <!--- end load -->

</head>
<body>
    <h1>Fruits vs Calories</h1>
    {% include_container chartcontainer %}

</body>

mysite/polls/templates/polls/promo_section.html
        <!-- ******PROMO****** -->
    <section id="promo" class="promo section offset-header">
        <div class="container text-center">
            <h2 class="title">dev<span class="highlight">Aid</span></h2>
            <p class="intro">A free mobile-friendly Bootstrap theme designed to help developers
promote their personal projects</p>
            <div class="btns">
                <a class="btn btn-cta-secondary" href="http://themes.3rdwavemedia.com/" target="_blank">Demo</a>
                <a class="btn btn-cta-primary" href="http://themes.3rdwavemedia.com/website-templates/devaid-free-bootstrap-theme-developers/" target="_blank">Download</a>
            </div>
            <ul class="meta list-inline">
                <li><a href="#" target="_blank">View on GitHub</a></li>
                <li><a href="https://github.com/twbs/bootstrap" target="_blank">Full Documentation</a></li>
                <li>Created by: <a href="http://themes.3rdwavemedia.com/" target="_blank">Xiaoying Riley</a> at 3rd Wave Media</li>
            </ul><!--//meta-->
        </div><!--//container-->
        <div class="social-media">
            <div class="social-media-inner container text-center">
                <ul class="list-inline">
                    <li class="twitter-follow"><a href="https://twitter.com/3rdwave_themes" class="twitter-follow-button" data-show-count="false">Follow @3rdwave_themes</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </li><!--//twitter-follow-->
                    <li class="twitter-tweet">
                        <a href="https://twitter.com/share" class="twitter-share-button" data-via="3rdwave_themes" data-hashtags="bootstrap">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </li><!--//twitter-tweet-->
                    <li class="facebook-like">
                         <div class="fb-like" data-href="http://themes.3rdwavemedia.com/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
                    </li><!--//facebook-like-->
                    <!--// Generate github buttons: https://github.com/mdo/github-buttons -->
                    <li class="github-star"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="110" height="20"></iframe></li>
                    <li class="github-fork"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=fork" allowtransparency="true" frameborder="0" scrolling="0" width="53" height="20"></iframe></li>
                    <!--//
                    <li class="github-follow"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&type=follow&count=true"
  allowtransparency="true" frameborder="0" scrolling="0" width="165" height="20"></iframe></li>
                    -->
                </ul>
            </div>
        </div>
    </section><!--//promo-->

mysite/polls/templates/polls/scatterChart.html
<div id="test1" class='with-3d-shadow with-transitions' style="width: 800px; height: 800px">
    <svg></svg>
</div>

<script>

    // register our custom symbols to nvd3
    // make sure your path is valid given any size because size scales if the chart scales.
    nv.utils.symbolMap.set('thin-x', function(size) {
        size = Math.sqrt(size);
        return 'T' + (-size/2) + ',' + (-size/2) +
                'l' + size + ',' + size +
                'm0,' + -(size) +
                'l' + (-size) + ',' + size;
    });

    // create the chart
    var chart;
    nv.addGraph(function() {
        chart = nv.models.scatterChart()
            .showDistX(true)
            .showDistY(true)
            .useVoronoi(true)
            .color(d3.scale.category10().range())
            .duration(300)
        ;
        chart.dispatch.on('renderEnd', function(){
            console.log('render complete');
        });

        chart.xAxis.tickFormat(d3.format('.02f'));
        chart.yAxis.tickFormat(d3.format('.02f'));
        chart.tooltipContent(function(key) {
            return '<h2>' + key + '</h2>';
        });

        d3.select('#test1 svg')
            .datum(randomData(4,40))
            .call(chart);

        nv.utils.windowResize(chart.update);

        chart.dispatch.on('stateChange', function(e) { ('New State:', JSON.stringify(e)); });
        return chart;
    });


    function randomData2(groups, points) { //# groups,# points per group
        // smiley and thin-x are our custom symbols!
        var data = [],
            // shapes = ['thin-x', 'circle', 'cross', 'triangle-up', 'triangle-down', 'diamond', 'square'],
            shapes = ['circle'],
            random = d3.random.normal();

        for (i = 0; i < groups; i++) {
            data.push({
                key: 'Group ' + i+ random(),
                values: []
            });

            for (j = 0; j < points; j++) {
                data[i].values.push({
                    x: random(),
                    y: random(),
                    size: Math.round(Math.random() * 100) / 100,
                    shape: shapes[j % shapes.length]
                });
            }
        }

        return data;
    }

</script>

mysite/polls/templates/polls/twitter_about.html
{% extends "main.html" %}
{% load static %}


{% block extra_header %}
{% endblock %}

{%block content %}
<section id="about" class="about section">
    <div class="container">
        <h2 class="title text-center">What is Erithacus pardus?</h2>
        <p class="intro text-center">
            It is a project for the class of Artificial Intelligence, the main purpose is to analyze the affect, mood or emotion
            in a tweet. The project is currently being developed in order to have more data and more ways to provide more
            information via a single tweet.
        </p>
        <div class="row">
            <div class="item col-md-4 col-sm-6 col-xs-12">
                <div class="icon-holder">
                    <i class="fa fa-coffee"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Why?</h3>
                    <p> Because we love Artificial intelligence.
                        One of the goals is to apply the knowledge into a project that can help or be helpful
                        in any area. Therefore, this project does not have a commercial purpose.
                    </p>
                </div><!--//content-->

            </div><!--//item-->
            <div class="item col-md-4 col-sm-6 col-xs-12">
                <div class="icon-holder">
                    <i class="fa fa-clock-o"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Time</h3>
                    <p>The time period of development is not only for the course.
                        The main idea is to keep developing this project.
                        We are looking for more ideas and more interesting things.
                    </p>
                </div><!--//content-->
            </div><!--//item-->
            <div class="item col-md-4 col-sm-6 col-xs-12">
                <div class="icon-holder">
                    <i class="fa fa-crosshairs"></i>
                </div>
                <div class="content">
                    <h3 class="sub-title">Main point</h3>
                    <p>It is focus on determine the affect and also to provide more information about
                    the person who is witting the tweet. The main point in this project is to detect
                    if a person has suicide tendencies, terrorism or any other destructive behavior. </p>
                </div><!--//content-->
            </div><!--//item-->
        </div><!--//row-->
    </div><!--//container-->
</section><!--//about-->

{% endblock %}

mysite/polls/templates/polls/twitter_graphs.html
{% extends "main.html" %}
{% load static %}


{% block extra_header %}

{% endblock %}

{%block content %}
    <!-- ******DOCS****** -->
    <section id="docs" class="docs section">
        <div class="container">
            <div class="docs-inner">
            <h2 class="title text-center">Graphs</h2>
            <div class="block">
                <h3 class="sub-title text-center">Data</h3>
                <p>This section is going to provide some graphs from the data stored in the database.
                    The first graph is showing the frequency by cluster. Each cluster is made by a number of words that
                    represent an affect(cluster).
                </p>
            </div><!--//block-->
            <p align="center"><img align="center" src="{% static "images/plot/count_by_cluster_0.png" %}" width="400"></p>

            <div class="block">
                <h3 class="sub-title text-center">Word Frequency</h3>
                <p>The next graph, shows the word frequency in the tweets already proccessed, with this graph is possible
                to see what are the words most used. The graph is limited to 1000 words</p>

            </div><!--//block-->
            <p align="center"><img align="center" src="{% static "images/plot/count_by_words.png" %}" width="400"></p>
            <div class="block">
                <h3 class="sub-title text-center">Tweets distribution</h3>
                <p>In order to see how the tweets are distributed, the next graph shows how the tweets are mapped
                according to the clusters selected.</p>
            </div><!--//block-->
                <p align="center"><img align="center" src="{% static "images/plot/a_tweets_map.png" %}" width="400"></p>
                <p align="center"><img align="center" src="{% static "images/plot/Valence x, Arousal y-K10.png" %}" width="400"></p>

            </div><!--//docs-inner-->
        </div><!--//container-->
    </section><!--//features-->

{% endblock %}

mysite/polls/templates/polls/twitter_home.html
{% extends "main.html" %}

{% block content %}

    <!-- ******PROMO****** -->
    <section id="promo" class="promo section offset-header">
        <div class="container text-center">
            <h2 class="title">Erithacus<span class="highlight"> pardus</span></h2>
            <p class="intro">
                Twiiter Analizer
                <div style="font-style:italic; font-size: medium; color: #2A8889;">
                    Pecho rojo, cabeza de fuego
                </div>
            </p>

            <div class="btns">
{#                <a class="btn btn-cta-secondary" href="http://themes.3rdwavemedia.com/" target="_blank">Demo</a>#}
                <a class="btn btn-cta-primary" href="{% url "polls1:about" %}" >Enter</a>
            </div>
            <ul class="meta list-inline">
{#                <li><a href="#" target="_blank">View on GitHub</a></li>#}
{#                <li><a href="" target="_blank">Full Documentation</a></li>#}
                <li>This Template was created by: <a href="http://themes.3rdwavemedia.com/" target="_blank">Xiaoying Riley</a> at 3rd Wave Media</li>
            </ul><!--//meta-->
        </div><!--//container-->

        <div class="social-media">
            <div class="social-media-inner container text-center">
                Xiaoying Riley Contact:
                <ul class="list-inline">
                    <li class="twitter-follow"><a href="https://twitter.com/3rdwave_themes" class="twitter-follow-button" data-show-count="false">Follow @3rdwave_themes</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </li><!--//twitter-follow-->
                    <li class="twitter-tweet">
                        <a href="https://twitter.com/share" class="twitter-share-button" data-via="3rdwave_themes" data-hashtags="bootstrap">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </li><!--//twitter-tweet-->
                    <li class="facebook-like">
                         <div class="fb-like" data-href="http://themes.3rdwavemedia.com/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
                    </li><!--//facebook-like-->
                    <!--// Generate github buttons: https://github.com/mdo/github-buttons -->
                    <li class="github-star"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="110" height="20"></iframe></li>
                    <li class="github-fork"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=fork" allowtransparency="true" frameborder="0" scrolling="0" width="53" height="20"></iframe></li>
                    <!--//
                    <li class="github-follow"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&type=follow&count=true"
  allowtransparency="true" frameborder="0" scrolling="0" width="165" height="20"></iframe></li>
                    -->
                </ul>
            </div>
        </div>

        <div class="social-media">
            <div class="social-media-inner container text-center">
                Erithacus-Pardus Contact:
                <ul class="list-inline">
                    <li class="twitter-follow">
                        <a href="https://twitter.com/Predator092" class="twitter-follow-button" data-show-count="false">Follow me</a>
                            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </li><!--//twitter-follow-->
{#                    <li class="twitter-tweet">#}
{#                        <a href="https://twitter.com/share" class="twitter-share-button" data-via="3rdwave_themes" data-hashtags="bootstrap">Tweet</a>#}
{#    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>#}
{#                    </li><!--//twitter-tweet-->#}
{#                    <li class="facebook-like">#}
{#                         <div class="fb-like" data-href="http://themes.3rdwavemedia.com/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>#}
{#                    </li><!--//facebook-like-->#}
                    <!--// Generate github buttons: https://github.com/mdo/github-buttons -->
{#                    <li class="github-star"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="110" height="20"></iframe></li>#}
{#                    <li class="github-fork"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=fork" allowtransparency="true" frameborder="0" scrolling="0" width="53" height="20"></iframe></li>#}
                    <!--//
                    <li class="github-follow"><iframe src="http://ghbtns.com/github-btn.html?user=mdo&type=follow&count=true"
  allowtransparency="true" frameborder="0" scrolling="0" width="165" height="20"></iframe></li>
                    -->
                </ul>
            </div>
        </div>
    </section><!--//promo-->

{% endblock %}

mysite/templates/footer.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<!-- ******CONTACT****** -->
    <section id="contact" class="contact section has-pattern">

    </section><!--//contact-->
<!-- ******FOOTER****** -->
    <footer class="footer">
        <div class="container text-center">
            <small class="copyright">Designed with <i class="fa fa-heart"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
        </div><!--//container-->
    </footer><!--//footer-->
     
    <!-- Javascript -->          
    <script type="text/javascript" src="{% static "plugins/bootstrap/js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "plugins/prism/prism.js" %}"></script>
    <script type="text/javascript" src="{% static "js/main.js" %}"></script>

mysite/templates/menu_section.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!-- ******HEADER****** -->
    <header id="header" class="header">
        <div class="container">
            <h1 class="logo pull-left">
                <a  href="{% url "polls1:home" %}">
                    <img src="{% static "erithacus.png" %}" width="40:" />
                    <span class="logo-title">Erithacus pardus</span>
                </a>
            </h1><!--//logo-->
            <nav id="main-nav" class="main-nav navbar-right" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><!--//nav-toggle-->
                </div><!--//navbar-header-->
                <div class="navbar-collapse collapse" id="navbar-collapse">
                    <ul class="nav navbar-nav">
{#                        <li class="active nav-item sr-only"><a class="scrollto" href="#promo">Home</a></li>#}
{#                        <li class="nav-item"><a class="scrollto" href="#about">About</a></li>#}
{#                        <li class="nav-item"><a class="scrollto" href="#features">Features</a></li>#}
{#                        <li class="nav-item"><a class="scrollto" href="#docs">Docs</a></li>#}
{#                        <li class="nav-item"><a class="scrollto" href="#license">License</a></li>#}
{#                        <li class="nav-item last"><a class="scrollto" href="#contact">Contact</a></li>#}
                        <li class="nav-item last"><a  href="{% url "polls1:about" %}" >About</a></li>
                     
                    </ul><!--//nav-->
                </div><!--//navabr-collapse-->
            </nav><!--//main-nav-->
        </div>
    </header><!--//header-->